return {
  {
    {
      name = "take-recorder",
      x = 300,
      y = 3,
      w = 22,
      h = 58,
      orig_w = 64,
      orig_h = 64,
      offset_x = 20,
      offset_y = 3
    },
    {
      name = "take_down1",
      x = 324,
      y = 2,
      w = 22,
      h = 59,
      orig_w = 64,
      orig_h = 64,
      offset_x = 21,
      offset_y = 3
    },
    {
      name = "take_down2",
      x = 918,
      y = 28,
      w = 20,
      h = 33,
      orig_w = 64,
      orig_h = 64,
      offset_x = 26,
      offset_y = 29
    },
    {
      name = "take_up1",
      x = 324,
      y = 2,
      w = 22,
      h = 59,
      orig_w = 64,
      orig_h = 64,
      offset_x = 21,
      offset_y = 3
    },
    {
      name = "take_up2",
      x = 2,
      y = 2,
      w = 30,
      h = 59,
      orig_w = 64,
      orig_h = 64,
      offset_x = 21,
      offset_y = 3
    },
    {
      name = "talk1",
      x = 324,
      y = 2,
      w = 22,
      h = 59,
      orig_w = 64,
      orig_h = 64,
      offset_x = 21,
      offset_y = 3
    },
    {
      name = "talk10",
      x = 324,
      y = 2,
      w = 22,
      h = 59,
      orig_w = 64,
      orig_h = 64,
      offset_x = 21,
      offset_y = 3
    },
    {
      name = "talk11",
      x = 396,
      y = 2,
      w = 22,
      h = 59,
      orig_w = 64,
      orig_h = 64,
      offset_x = 21,
      offset_y = 3
    },
    {
      name = "talk12",
      x = 396,
      y = 2,
      w = 22,
      h = 59,
      orig_w = 64,
      orig_h = 64,
      offset_x = 21,
      offset_y = 3
    },
    {
      name = "talk2",
      x = 348,
      y = 2,
      w = 22,
      h = 59,
      orig_w = 64,
      orig_h = 64,
      offset_x = 21,
      offset_y = 3
    },
    {
      name = "talk3",
      x = 372,
      y = 2,
      w = 22,
      h = 59,
      orig_w = 64,
      orig_h = 64,
      offset_x = 21,
      offset_y = 3
    },
    {
      name = "talk4",
      x = 324,
      y = 2,
      w = 22,
      h = 59,
      orig_w = 64,
      orig_h = 64,
      offset_x = 21,
      offset_y = 3
    },
    {
      name = "talk5",
      x = 324,
      y = 2,
      w = 22,
      h = 59,
      orig_w = 64,
      orig_h = 64,
      offset_x = 21,
      offset_y = 3
    },
    {
      name = "talk6",
      x = 396,
      y = 2,
      w = 22,
      h = 59,
      orig_w = 64,
      orig_h = 64,
      offset_x = 21,
      offset_y = 3
    },
    {
      name = "talk7",
      x = 420,
      y = 2,
      w = 22,
      h = 59,
      orig_w = 64,
      orig_h = 64,
      offset_x = 21,
      offset_y = 3
    },
    {
      name = "talk8",
      x = 444,
      y = 2,
      w = 22,
      h = 59,
      orig_w = 64,
      orig_h = 64,
      offset_x = 21,
      offset_y = 3
    },
    {
      name = "talk9",
      x = 468,
      y = 2,
      w = 22,
      h = 59,
      orig_w = 64,
      orig_h = 64,
      offset_x = 21,
      offset_y = 3
    },
    {
      name = "talk_down1",
      x = 104,
      y = 3,
      w = 26,
      h = 58,
      orig_w = 64,
      orig_h = 64,
      offset_x = 20,
      offset_y = 3
    },
    {
      name = "talk_down2",
      x = 132,
      y = 3,
      w = 26,
      h = 58,
      orig_w = 64,
      orig_h = 64,
      offset_x = 20,
      offset_y = 3
    },
    {
      name = "talk_down3",
      x = 132,
      y = 3,
      w = 26,
      h = 58,
      orig_w = 64,
      orig_h = 64,
      offset_x = 20,
      offset_y = 3
    },
    {
      name = "talk_down4",
      x = 104,
      y = 3,
      w = 26,
      h = 58,
      orig_w = 64,
      orig_h = 64,
      offset_x = 20,
      offset_y = 3
    },
    {
      name = "talk_down5",
      x = 104,
      y = 3,
      w = 26,
      h = 58,
      orig_w = 64,
      orig_h = 64,
      offset_x = 20,
      offset_y = 3
    },
    {
      name = "talk_down6",
      x = 132,
      y = 3,
      w = 26,
      h = 58,
      orig_w = 64,
      orig_h = 64,
      offset_x = 20,
      offset_y = 3
    },
    {
      name = "talk_down7",
      x = 160,
      y = 3,
      w = 26,
      h = 58,
      orig_w = 64,
      orig_h = 64,
      offset_x = 20,
      offset_y = 3
    },
    {
      name = "talk_down8",
      x = 132,
      y = 3,
      w = 26,
      h = 58,
      orig_w = 64,
      orig_h = 64,
      offset_x = 20,
      offset_y = 3
    },
    {
      name = "talk_down9",
      x = 188,
      y = 3,
      w = 26,
      h = 58,
      orig_w = 64,
      orig_h = 64,
      offset_x = 20,
      offset_y = 3
    },
    {
      name = "walk_down1",
      x = 104,
      y = 3,
      w = 26,
      h = 58,
      orig_w = 64,
      orig_h = 64,
      offset_x = 20,
      offset_y = 3
    },
    {
      name = "walk_down2",
      x = 492,
      y = 5,
      w = 21,
      h = 56,
      orig_w = 64,
      orig_h = 64,
      offset_x = 22,
      offset_y = 5
    },
    {
      name = "walk_down3",
      x = 670,
      y = 6,
      w = 19,
      h = 55,
      orig_w = 64,
      orig_h = 64,
      offset_x = 23,
      offset_y = 6
    },
    {
      name = "walk_down4",
      x = 691,
      y = 7,
      w = 20,
      h = 54,
      orig_w = 64,
      orig_h = 64,
      offset_x = 23,
      offset_y = 7
    },
    {
      name = "walk_down5",
      x = 538,
      y = 5,
      w = 20,
      h = 56,
      orig_w = 64,
      orig_h = 64,
      offset_x = 23,
      offset_y = 5
    },
    {
      name = "walk_down6",
      x = 515,
      y = 5,
      w = 21,
      h = 56,
      orig_w = 64,
      orig_h = 64,
      offset_x = 23,
      offset_y = 5
    },
    {
      name = "walk_down7",
      x = 735,
      y = 6,
      w = 19,
      h = 55,
      orig_w = 64,
      orig_h = 64,
      offset_x = 24,
      offset_y = 6
    },
    {
      name = "walk_down8",
      x = 713,
      y = 7,
      w = 20,
      h = 54,
      orig_w = 64,
      orig_h = 64,
      offset_x = 23,
      offset_y = 7
    },
    {
      name = "walk_down9",
      x = 560,
      y = 5,
      w = 20,
      h = 56,
      orig_w = 64,
      orig_h = 64,
      offset_x = 23,
      offset_y = 5
    },
    {
      name = "walk_right1",
      x = 324,
      y = 2,
      w = 22,
      h = 59,
      orig_w = 64,
      orig_h = 64,
      offset_x = 21,
      offset_y = 3
    },
    {
      name = "walk_right2",
      x = 34,
      y = 5,
      w = 33,
      h = 56,
      orig_w = 64,
      orig_h = 64,
      offset_x = 16,
      offset_y = 5
    },
    {
      name = "walk_right3",
      x = 244,
      y = 6,
      w = 26,
      h = 55,
      orig_w = 64,
      orig_h = 64,
      offset_x = 19,
      offset_y = 6
    },
    {
      name = "walk_right4",
      x = 756,
      y = 7,
      w = 19,
      h = 54,
      orig_w = 64,
      orig_h = 64,
      offset_x = 22,
      offset_y = 7
    },
    {
      name = "walk_right5",
      x = 880,
      y = 5,
      w = 17,
      h = 56,
      orig_w = 64,
      orig_h = 64,
      offset_x = 24,
      offset_y = 5
    },
    {
      name = "walk_right6",
      x = 69,
      y = 5,
      w = 33,
      h = 56,
      orig_w = 64,
      orig_h = 64,
      offset_x = 16,
      offset_y = 5
    },
    {
      name = "walk_right7",
      x = 272,
      y = 6,
      w = 26,
      h = 55,
      orig_w = 64,
      orig_h = 64,
      offset_x = 19,
      offset_y = 6
    },
    {
      name = "walk_right8",
      x = 777,
      y = 7,
      w = 19,
      h = 54,
      orig_w = 64,
      orig_h = 64,
      offset_x = 22,
      offset_y = 7
    },
    {
      name = "walk_right9",
      x = 899,
      y = 5,
      w = 17,
      h = 56,
      orig_w = 64,
      orig_h = 64,
      offset_x = 24,
      offset_y = 5
    },
    {
      name = "walk_up1",
      x = 216,
      y = 3,
      w = 26,
      h = 58,
      orig_w = 64,
      orig_h = 64,
      offset_x = 20,
      offset_y = 3
    },
    {
      name = "walk_up2",
      x = 582,
      y = 5,
      w = 20,
      h = 56,
      orig_w = 64,
      orig_h = 64,
      offset_x = 23,
      offset_y = 5
    },
    {
      name = "walk_up3",
      x = 840,
      y = 6,
      w = 18,
      h = 55,
      orig_w = 64,
      orig_h = 64,
      offset_x = 24,
      offset_y = 6
    },
    {
      name = "walk_up4",
      x = 798,
      y = 7,
      w = 19,
      h = 54,
      orig_w = 64,
      orig_h = 64,
      offset_x = 23,
      offset_y = 7
    },
    {
      name = "walk_up5",
      x = 604,
      y = 5,
      w = 20,
      h = 56,
      orig_w = 64,
      orig_h = 64,
      offset_x = 22,
      offset_y = 5
    },
    {
      name = "walk_up6",
      x = 626,
      y = 5,
      w = 20,
      h = 56,
      orig_w = 64,
      orig_h = 64,
      offset_x = 23,
      offset_y = 5
    },
    {
      name = "walk_up7",
      x = 860,
      y = 6,
      w = 18,
      h = 55,
      orig_w = 64,
      orig_h = 64,
      offset_x = 24,
      offset_y = 6
    },
    {
      name = "walk_up8",
      x = 819,
      y = 7,
      w = 19,
      h = 54,
      orig_w = 64,
      orig_h = 64,
      offset_x = 24,
      offset_y = 7
    },
    {
      name = "walk_up9",
      x = 648,
      y = 5,
      w = 20,
      h = 56,
      orig_w = 64,
      orig_h = 64,
      offset_x = 24,
      offset_y = 5
    },
    filename = "ines.png"
  }
}