return {
  {
    {
      name = "arrow",
      x = 32,
      y = 2,
      w = 4,
      h = 7,
      orig_w = 4,
      orig_h = 7,
      offset_x = 0,
      offset_y = 0
    },
    {
      name = "arrow_on",
      x = 38,
      y = 2,
      w = 4,
      h = 7,
      orig_w = 4,
      orig_h = 7,
      offset_x = 0,
      offset_y = 0
    },
    {
      name = "back",
      x = 74,
      y = 31,
      w = 14,
      h = 11,
      orig_w = 24,
      orig_h = 24,
      offset_x = 5,
      offset_y = 6
    },
    {
      name = "bag",
      x = 2,
      y = 52,
      w = 24,
      h = 24,
      orig_w = 24,
      orig_h = 24,
      offset_x = 0,
      offset_y = 0
    },
    {
      name = "button1",
      x = 41,
      y = 12,
      w = 1,
      h = 15,
      orig_w = 1,
      orig_h = 15,
      offset_x = 0,
      offset_y = 0
    },
    {
      name = "button2",
      x = 84,
      y = 14,
      w = 1,
      h = 15,
      orig_w = 1,
      orig_h = 15,
      offset_x = 0,
      offset_y = 0
    },
    {
      name = "button_side",
      x = 87,
      y = 5,
      w = 1,
      h = 13,
      orig_w = 1,
      orig_h = 15,
      offset_x = 0,
      offset_y = 1
    },
    {
      name = "cassette",
      x = 74,
      y = 44,
      w = 18,
      h = 12,
      orig_w = 24,
      orig_h = 24,
      offset_x = 3,
      offset_y = 6
    },
    {
      name = "cassette_old",
      x = 44,
      y = 32,
      w = 18,
      h = 12,
      orig_w = 24,
      orig_h = 24,
      offset_x = 3,
      offset_y = 6
    },
    {
      name = "check_off",
      x = 28,
      y = 47,
      w = 20,
      h = 9,
      orig_w = 20,
      orig_h = 9,
      offset_x = 0,
      offset_y = 0
    },
    {
      name = "check_on",
      x = 50,
      y = 46,
      w = 20,
      h = 9,
      orig_w = 20,
      orig_h = 9,
      offset_x = 0,
      offset_y = 0
    },
    {
      name = "cog",
      x = 74,
      y = 58,
      w = 18,
      h = 18,
      orig_w = 18,
      orig_h = 18,
      offset_x = 0,
      offset_y = 0
    },
    {
      name = "coin",
      x = 64,
      y = 31,
      w = 8,
      h = 13,
      orig_w = 24,
      orig_h = 24,
      offset_x = 8,
      offset_y = 6
    },
    {
      name = "cursor_interact",
      x = 57,
      y = 4,
      w = 9,
      h = 9,
      orig_w = 11,
      orig_h = 11,
      offset_x = 1,
      offset_y = 1
    },
    {
      name = "cursor_normal",
      x = 68,
      y = 4,
      w = 9,
      h = 9,
      orig_w = 11,
      orig_h = 11,
      offset_x = 1,
      offset_y = 1
    },
    {
      name = "device_new",
      x = 26,
      y = 29,
      w = 16,
      h = 16,
      orig_w = 24,
      orig_h = 24,
      offset_x = 4,
      offset_y = 5
    },
    {
      name = "device_new2",
      x = 26,
      y = 29,
      w = 16,
      h = 16,
      orig_w = 24,
      orig_h = 24,
      offset_x = 4,
      offset_y = 5
    },
    {
      name = "device_old",
      x = 23,
      y = 11,
      w = 16,
      h = 16,
      orig_w = 24,
      orig_h = 24,
      offset_x = 4,
      offset_y = 5
    },
    {
      name = "guitar",
      x = 52,
      y = 57,
      w = 20,
      h = 19,
      orig_w = 24,
      orig_h = 24,
      offset_x = 2,
      offset_y = 4
    },
    {
      name = "navigator",
      x = 2,
      y = 29,
      w = 22,
      h = 21,
      orig_w = 24,
      orig_h = 24,
      offset_x = 1,
      offset_y = 2
    },
    {
      name = "pick",
      x = 44,
      y = 17,
      w = 12,
      h = 13,
      orig_w = 24,
      orig_h = 24,
      offset_x = 6,
      offset_y = 5
    },
    {
      name = "pickup",
      x = 28,
      y = 58,
      w = 22,
      h = 18,
      orig_w = 24,
      orig_h = 24,
      offset_x = 1,
      offset_y = 3
    },
    {
      name = "recorder",
      x = 2,
      y = 6,
      w = 19,
      h = 21,
      orig_w = 24,
      orig_h = 24,
      offset_x = 3,
      offset_y = 2
    },
    {
      name = "scroll_down",
      x = 58,
      y = 15,
      w = 11,
      h = 14,
      orig_w = 15,
      orig_h = 24,
      offset_x = 2,
      offset_y = 5
    },
    {
      name = "scroll_up",
      x = 71,
      y = 15,
      w = 11,
      h = 14,
      orig_w = 15,
      orig_h = 24,
      offset_x = 2,
      offset_y = 5
    },
    {
      name = "slider1",
      x = 90,
      y = 37,
      w = 1,
      h = 5,
      orig_w = 1,
      orig_h = 9,
      offset_x = 0,
      offset_y = 2
    },
    {
      name = "slider2",
      x = 79,
      y = 8,
      w = 1,
      h = 5,
      orig_w = 1,
      orig_h = 9,
      offset_x = 0,
      offset_y = 2
    },
    {
      name = "slider_marker",
      x = 87,
      y = 20,
      w = 5,
      h = 9,
      orig_w = 5,
      orig_h = 9,
      offset_x = 0,
      offset_y = 0
    },
    {
      name = "slider_side",
      x = 90,
      y = 32,
      w = 1,
      h = 3,
      orig_w = 1,
      orig_h = 9,
      offset_x = 0,
      offset_y = 3
    },
    {
      name = "ui_bg_normal",
      x = 23,
      y = 2,
      w = 7,
      h = 7,
      orig_w = 7,
      orig_h = 7,
      offset_x = 0,
      offset_y = 0
    },
    {
      name = "ui_bg_selected",
      x = 44,
      y = 4,
      w = 11,
      h = 11,
      orig_w = 11,
      orig_h = 11,
      offset_x = 0,
      offset_y = 0
    },
    {
      name = "ui_mouse_lmb",
      x = 0,
      y = 77,
      w = 11,
      h = 15,
      orig_w = 11,
      orig_h = 15,
      offset_x = 0,
      offset_y = 0
    },
    {
      name = "ui_mouse_rmb",
      x = 11,
      y = 77,
      w = 11,
      h = 15,
      orig_w = 11,
      orig_h = 15,
      offset_x = 0,
      offset_y = 0
    },
    filename = "interface.png"
  }
}